// <auto-generated />
namespace AmritTulya.EntityLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class NothingChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NothingChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300933473_Nothing Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
